//
// Created by Víctor Jiménez Rugama on 12/24/21.
//

#ifndef CYDI4_TABSELECTED_H
#define CYDI4_TABSELECTED_H
#include "../base.h"
enum tabSelected
{
    HOME=HOMEVIEW,SOURCES=REPOSITORYVIEW, INSTALLED=DOWNLOADVIEW , SEARCH=PACKAGESEARCHVIEW, SETTINGS=SETTINGSVIEW
};
#endif //CYDI4_TABSELECTED_H
